Update eks-dev-deployment.yaml

diff --git a/.github/workflows/eks-dev-deployment.yaml b/.github/workflows/eks-dev-deployment.yaml
--- a/.github/workflows/eks-dev-deployment.yaml
+++ b/.github/workflows/eks-dev-deployment.yaml
@@ -29,13 +29,8 @@ jobs:
           ls -ltra
           yarn install
           yarn run build
-          ls -ltra
-      - name: Ensure dist/ directory exists
-        run: |
-          if [ ! -d dist ]; then
-            echo "dist/ directory not found. Creating it."
-            mkdir -p dist
-          fi
+          ls -ltra 
+          ls -ltra dist
       # Ensure dist/ directory exists
       - name: Verify dist/ directory
         run: |
@@ -44,20 +39,8 @@ jobs:
             mkdir dist
           fi
 
-            # Create Dockerfile in dist/
       - name: Create Dockerfile in dist/
         run: |
-          if [ -z "${{ secrets.DOCKERFILE_DEV }}" ]; then
-            echo "Error: DOCKERFILE_DEV secret is empty."
-            exit 1
-          fi
-
-          # Write the Dockerfile content safely
-          echo "${{ secrets.DOCKERFILE_DEV }}" | sed 's/\r$//' > dist/Dockerfile
-
-          echo "Dockerfile created in dist/:"
-          cat dist/Dockerfile
-
           # Copy nginx.conf if it exists
           if [ -f nginx.conf ]; then
             cp nginx.conf dist/
@@ -66,6 +49,15 @@ jobs:
             echo "Error: nginx.conf not found in the repository."
             exit 1
           fi
+          # Copy Dockerfile if it exists
+          if [ -f Dockerfile ]; then
+            cp Dockerfile dist/
+            echo "Dockerfile copied to dist/"
+          else
+            echo "Error: Dockerfile not found in the repository."
+            exit 1
+          fi
+
       # Log in to Docker Hub
       - name: Log in to Docker Hub
         run: |
@@ -74,6 +66,7 @@ jobs:
       # Build and push Docker image
       - name: Build and Push Docker Image
         run: |
+          ls -ltra dist
           cd dist/
           docker build -t ${{ secrets.DOCKER_REPO_NAME_DEV }}:${{ secrets.DOCKER_IMAGE_DEV }} .
           docker push ${{ secrets.DOCKER_REPO_NAME_DEV }}:${{ secrets.DOCKER_IMAGE_DEV }}
